services:
  back:
    build: ./back
    volumes:
      - crp-db:/db
    ports:
      - "6000:6000"
      - "4443:4443"
    networks:
      - base
  bot:
    build: ./bot
    volumes:
      - crp-db:/usr/src/app/database
    networks:
      - base
    depends_on:
      - back

  database:
    image: postgres
    environment:
      POSTGRES_DB: "gpus"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "sadpguser123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg-db:

networks:
  base:
    driver: bridge